FROM alpine:3.7

ENV HUGO_VERSION=0.36.1
RUN apk add --no-cache curl
RUN curl -sL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar zx

ENTRYPOINT ["/hugo"]